# Site Settings
locale                   : "es_ES"
title                    : "Estrategias digitales"
title_separator          : "|"
name                     : "Emirodgar"
twitter_username: emirodgar
github_username:  emirodgar
